export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const RMV_INGREDIENT = 'RMV_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FAILED_FETCH_INGREDIENTS = 'FAILED_FETCHING_INGREDIENTS';

export const START_PURCHASE = 'START_PURCHASE';
export const SUCCESS_PURCHASE = 'SUCCESS_PURCHASE';
export const FAIL_PURCHASE = 'FAIL_PURCHASE';
export const INIT_PURCHASE = 'INIT_PURCHASE';

export const FETCH_ORDERS = 'FECH_ORDERS';
export const SUCCESSED_FETCH_ORDERS = 'SUCCESSED_FETCH_ORDERS';
export const FAILED_FETCH_ORDERS = 'FAILED_FETCH_ORDERS';

export const START_AUTH = 'START_AUTH';
export const SUCCESS_AUTH = 'SUCCESS_AUTH';
export const FAIL_AUTH = 'FAIL_AUTH';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
